version: '3.6'
services:
    postgres:
        image: postgres
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=root
        ports:
            - "5432:5432"
        restart: always
        volumes:
            - ./0001_users.sql:/docker-entrypoint-initdb.d/0001_users.sql

    pgadmin-compose:
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
            - PGADMIN_DEFAULT_PASSWORD=admin
        ports:
            - '16543:80'
        depends_on:
            -   postgres